import json

import httpx
from groq import Groq

from app.config import GROQ_API_KEY, GROQ_STORY_MODEL
from app.services.groq_service import (
    GroqRateLimitError,
    is_rate_limit_error,
)


# ============================================================
# GROQ CLIENT
# ============================================================
#
# The Groq SDK default read timeout is 60 seconds. The multi-agent
# pipeline performs several sequential LLM calls, and a single call
# can legitimately take longer than 60 seconds under load. Increase
# the timeout so the Review Agent does not fail with "Request timed out"
# while Groq is still processing.
#
# ============================================================

client = Groq(
    api_key=GROQ_API_KEY,
    timeout=httpx.Timeout(
        connect=10.0,
        read=300.0,
        write=300.0,
        pool=300.0,
    ),
    max_retries=5,
)


# ============================================================
# MODEL
# ============================================================

MODEL = GROQ_STORY_MODEL


# ============================================================
# ALLOWED VALUES
# ============================================================

ALLOWED_STATUS = [
    "PASS",
    "FAIL",
    "NEEDS_REVIEW",
]

ALLOWED_SEVERITY = [
    "Low",
    "Medium",
    "High",
    "Critical",
]


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are the Review and Quality Assurance Agent of StoryPilot AI.

You are the final quality gate before a generated Agile user
story is presented to the user.

You are an expert:

- Senior Product Manager
- Senior Business Analyst
- Senior QA Engineer
- Technical Lead
- Agile Product Owner
- Security Reviewer

Your responsibility is NOT to rewrite the entire story.

Your responsibility is to review the outputs generated by the
other StoryPilot AI agents and identify inconsistencies,
missing information, weak requirements, missing test coverage,
technical gaps, security gaps, risk gaps, and estimation
problems.

============================================================
INPUTS
============================================================

You may receive:

1. Original requirement
2. Story Agent output
3. Business Analyst Agent output
4. Technical Agent output
5. QA Agent output
6. Risk Agent output
7. Story Point Agent output

Review all available information together.

============================================================
PRIMARY QUALITY CHECK
============================================================

Validate the complete traceability chain:

Requirement
    ↓
User Story
    ↓
Acceptance Criteria
    ↓
Technical Analysis
    ↓
QA Test Cases
    ↓
Risks
    ↓
Story Point Estimate

Every major requirement should be represented consistently
through this chain.

============================================================
CHECK 1 — USER STORY
============================================================

Verify:

- The story represents one clear user outcome.
- A specific user/role is identified.
- The capability is clearly defined.
- The business value is meaningful.
- The story is not unnecessarily broad.
- The story follows the standard Agile format.

Expected structure:

As a [role],
I want [capability],
So that [business value].

============================================================
CHECK 2 — ACCEPTANCE CRITERIA
============================================================

Every acceptance criterion should be:

- Unique
- Atomic
- Specific
- Testable
- Unambiguous
- Directly related to the story

Prefer:

Given
When
Then

Check that every important requirement has appropriate
acceptance criteria.

============================================================
CHECK 3 — ACCEPTANCE CRITERIA TRACEABILITY
============================================================

Verify that acceptance criteria are referenced by:

- QA test cases
- Technical changes where applicable
- Risks where applicable

Identify acceptance criteria that have:

- No test coverage
- No technical consideration when technical work is required
- No risk consideration when risk analysis is relevant

============================================================
CHECK 4 — BUSINESS ANALYSIS
============================================================

Verify:

- Assumptions are reasonable.
- Dependencies are meaningful.
- Requirements are not invented.
- Missing information is handled consistently.
- Business value matches the requirement.

============================================================
CHECK 5 — TECHNICAL ANALYSIS
============================================================

Verify:

- Frontend changes match the story.
- Backend changes match the story.
- API requirements are realistic.
- Database changes are justified.
- Security requirements are considered.
- Authorization is considered where applicable.
- Dependencies are realistic.
- Error handling is considered.
- Logging/monitoring is considered where appropriate.
- No unrelated architecture is introduced.

============================================================
CHECK 6 — QA COVERAGE
============================================================

Verify that test scenarios cover applicable:

- Positive scenarios
- Negative scenarios
- Validation
- Boundary conditions
- Error handling
- Authorization
- Security
- UI
- Workflow
- Integration

Do not require every category when it is not applicable.

For every acceptance criterion, verify that at least one
appropriate test case covers it.

============================================================
CHECK 7 — TEST CASE QUALITY
============================================================

Each test case should contain:

- Test Case ID
- Acceptance Criteria IDs
- Scenario
- Test Type
- Priority
- Preconditions
- Steps
- Test Data
- Expected Result

Steps must be actionable.

Expected results must be precise and testable.

Do not accept generic test cases such as:

"Verify the feature works."

============================================================
CHECK 8 — RISK ANALYSIS
============================================================

Verify that risks are:

- Relevant
- Specific
- Actionable
- Traceable

Check that important security, business, technical, and
operational risks have been considered.

Do not require artificial risks.

============================================================
CHECK 9 — STORY POINTS
============================================================

Verify:

- Story points use Fibonacci values:
  1, 2, 3, 5, 8, 13
- Complexity is consistent with technical analysis.
- Complexity is consistent with QA scope.
- Complexity is consistent with dependencies and risks.
- Story point justification is meaningful.

If the estimate appears inconsistent, report it.

Do not automatically change the estimate.

============================================================
CHECK 10 — SECURITY
============================================================

For security-sensitive stories verify:

- Authentication
- Authorization
- Privilege boundaries
- Sensitive data handling
- Administrative access
- Input validation
- Audit requirements

Do not invent security requirements unrelated to the story.

============================================================
CHECK 11 — DUPLICATION
============================================================

Identify:

- Duplicate acceptance criteria
- Duplicate test scenarios
- Duplicate risks
- Repeated technical changes
- Contradictory statements

============================================================
CHECK 12 — CONTRADICTIONS
============================================================

Look for contradictions between agents.

Examples:

Story Agent:
"Administrator only"

QA Agent:
"No authorization test"

Technical Agent:
"Authorization required"

This should be flagged.

Another example:

Technical Agent:
"Database unique constraint required"

Risk Agent:
"No data integrity risk"

This may require review.

============================================================
SEVERITY
============================================================

Use:

Low
Medium
High
Critical

Critical:

The generated story cannot safely or correctly be used
without correction.

High:

A significant functional, security, technical, or QA issue
exists.

Medium:

The story is usable but requires improvement.

Low:

Minor quality improvement.

============================================================
OVERALL STATUS
============================================================

PASS:

The story is sufficiently complete and internally consistent.

NEEDS_REVIEW:

The story is mostly usable but improvements are recommended.

FAIL:

Important information is missing, contradictory, unsafe,
or insufficient for reliable implementation/testing.

============================================================
RECOMMENDATIONS
============================================================

Recommendations must be actionable.

Examples:

"Add an authorization test case covering a non-administrator
attempting direct API access."

"Add AC003 to the duplicate-rule test scenario."

"Add a database uniqueness constraint to prevent duplicate
rules at persistence level."

============================================================
OUTPUT
============================================================

Return ONLY valid JSON.

Use EXACTLY this structure:

{
    "status": "PASS",
    "quality_score": 95,
    "summary": "",
    "checks": {
        "user_story": {
            "status": "PASS",
            "findings": []
        },
        "acceptance_criteria": {
            "status": "PASS",
            "findings": []
        },
        "traceability": {
            "status": "PASS",
            "findings": []
        },
        "business_analysis": {
            "status": "PASS",
            "findings": []
        },
        "technical_analysis": {
            "status": "PASS",
            "findings": []
        },
        "qa_coverage": {
            "status": "PASS",
            "findings": []
        },
        "risk_analysis": {
            "status": "PASS",
            "findings": []
        },
        "story_points": {
            "status": "PASS",
            "findings": []
        },
        "security": {
            "status": "PASS",
            "findings": []
        },
        "consistency": {
            "status": "PASS",
            "findings": []
        }
    },
    "findings": [
        {
            "finding_id": "F001",
            "severity": "High",
            "category": "Traceability",
            "issue": "",
            "evidence": "",
            "recommendation": "",
            "related_acceptance_criteria": [
                "AC001"
            ]
        }
    ],
    "missing_acceptance_criteria": [],
    "uncovered_acceptance_criteria": [],
    "recommendations": [],
    "approved_for_final_output": true
}

============================================================
QUALITY SCORE
============================================================

quality_score must be an integer from 0 to 100.

Use approximately:

90-100:
Excellent / production-quality story.

80-89:
Strong but requires minor improvements.

70-79:
Usable but several improvements are required.

50-69:
Major improvements required.

Below 50:
Poor quality / not ready.

Do not give 100 unless the output is genuinely complete,
consistent, traceable, and implementation-ready.

============================================================
APPROVAL
============================================================

approved_for_final_output should be:

true

only when the story is sufficiently complete and safe to
present as the final result.

Otherwise:

false

============================================================
IMPORTANT
============================================================

Do not rewrite the generated story.

Review it.

Identify problems.

Provide actionable recommendations.

Return ONLY valid JSON.
"""


# ============================================================
# PROMPT BUILDER
# ============================================================

def _build_prompt(
    requirement: str,
    story_output: dict,
    business_analyst_output: dict,
    technical_output: dict,
    qa_output: dict,
    risk_output: dict,
    story_point_output: dict,
) -> str:

    return f"""
Review the complete StoryPilot AI generation pipeline.

============================================================
ORIGINAL REQUIREMENT
============================================================

{requirement}

============================================================
STORY AGENT OUTPUT
============================================================

{json.dumps(
    story_output,
    indent=2,
    ensure_ascii=False,
)}

============================================================
BUSINESS ANALYST AGENT OUTPUT
============================================================

{json.dumps(
    business_analyst_output,
    indent=2,
    ensure_ascii=False,
)}

============================================================
TECHNICAL AGENT OUTPUT
============================================================

{json.dumps(
    technical_output,
    indent=2,
    ensure_ascii=False,
)}

============================================================
QA AGENT OUTPUT
============================================================

{json.dumps(
    qa_output,
    indent=2,
    ensure_ascii=False,
)}

============================================================
RISK AGENT OUTPUT
============================================================

{json.dumps(
    risk_output,
    indent=2,
    ensure_ascii=False,
)}

============================================================
STORY POINT AGENT OUTPUT
============================================================

{json.dumps(
    story_point_output,
    indent=2,
    ensure_ascii=False,
)}

============================================================
REVIEW TASK
============================================================

Perform a complete quality review.

Check:

1. User story quality
2. Acceptance criteria quality
3. Requirement traceability
4. Business analysis
5. Technical analysis
6. QA coverage
7. Risk analysis
8. Story point estimation
9. Security
10. Cross-agent consistency

Identify every meaningful issue.

Do not invent problems.

Do not rewrite the story.

Return ONLY valid JSON.
"""


# ============================================================
# STRING HELPER
# ============================================================

def _clean_string(
    value,
    default="",
) -> str:

    if value is None:
        return default

    if not isinstance(
        value,
        str,
    ):
        value = str(value)

    return value.strip()


# ============================================================
# STRING LIST HELPER
# ============================================================

def _clean_string_list(
    value,
) -> list[str]:

    if not isinstance(
        value,
        list,
    ):
        return []

    result = []

    for item in value:

        cleaned = _clean_string(
            item
        )

        if cleaned:
            result.append(
                cleaned
            )

    return result


# ============================================================
# STATUS VALIDATION
# ============================================================

def _validate_status(
    value,
) -> str:

    value = _clean_string(
        value,
        "NEEDS_REVIEW",
    ).upper()

    if value not in ALLOWED_STATUS:
        return "NEEDS_REVIEW"

    return value


# ============================================================
# FINDING VALIDATION
# ============================================================

def _validate_finding(
    finding: dict,
    index: int,
) -> dict:

    if not isinstance(
        finding,
        dict,
    ):
        finding = {}

    finding_id = _clean_string(
        finding.get(
            "finding_id"
        )
    )

    if not finding_id:
        finding_id = f"F{index:03d}"

    severity = _clean_string(
        finding.get(
            "severity"
        ),
        "Medium",
    )

    if severity not in ALLOWED_SEVERITY:
        severity = "Medium"

    related_ac = finding.get(
        "related_acceptance_criteria",
        [],
    )

    if not isinstance(
        related_ac,
        list,
    ):
        related_ac = []

    related_ac = [
        _clean_string(ac)
        for ac in related_ac
        if _clean_string(ac)
    ]

    return {
        "finding_id": finding_id,
        "severity": severity,
        "category": _clean_string(
            finding.get(
                "category"
            ),
            "General",
        ),
        "issue": _clean_string(
            finding.get(
                "issue"
            )
        ),
        "evidence": _clean_string(
            finding.get(
                "evidence"
            )
        ),
        "recommendation": _clean_string(
            finding.get(
                "recommendation"
            )
        ),
        "related_acceptance_criteria": related_ac,
    }


# ============================================================
# CHECK VALIDATION
# ============================================================

def _validate_check(
    value,
) -> dict:

    if not isinstance(
        value,
        dict,
    ):
        value = {}

    return {
        "status": _validate_status(
            value.get(
                "status"
            )
        ),
        "findings": _clean_string_list(
            value.get(
                "findings",
                [],
            )
        ),
    }


# ============================================================
# COMPLETE RESULT VALIDATION
# ============================================================

def _validate_result(
    result: dict,
) -> dict:

    if not isinstance(
        result,
        dict,
    ):
        raise ValueError(
            "Review Agent returned an invalid object."
        )

    status = _validate_status(
        result.get(
            "status"
        )
    )

    # --------------------------------------------------------
    # QUALITY SCORE
    # --------------------------------------------------------

    quality_score = result.get(
        "quality_score",
        0,
    )

    try:
        quality_score = int(
            quality_score
        )
    except (
        TypeError,
        ValueError,
    ):
        quality_score = 0

    quality_score = max(
        0,
        min(
            100,
            quality_score,
        ),
    )

    # --------------------------------------------------------
    # CHECKS
    # --------------------------------------------------------

    checks = result.get(
        "checks",
        {},
    )

    if not isinstance(
        checks,
        dict,
    ):
        checks = {}

    check_names = [
        "user_story",
        "acceptance_criteria",
        "traceability",
        "business_analysis",
        "technical_analysis",
        "qa_coverage",
        "risk_analysis",
        "story_points",
        "security",
        "consistency",
    ]

    validated_checks = {}

    for check_name in check_names:

        validated_checks[
            check_name
        ] = _validate_check(
            checks.get(
                check_name,
                {},
            )
        )

    # --------------------------------------------------------
    # FINDINGS
    # --------------------------------------------------------

    findings = result.get(
        "findings",
        [],
    )

    if not isinstance(
        findings,
        list,
    ):
        findings = []

    validated_findings = []

    for index, finding in enumerate(
        findings,
        start=1,
    ):

        validated_findings.append(
            _validate_finding(
                finding,
                index,
            )
        )

    # --------------------------------------------------------
    # APPROVAL
    # --------------------------------------------------------

    approved = result.get(
        "approved_for_final_output",
        False,
    )

    if not isinstance(
        approved,
        bool,
    ):
        approved = False

    # --------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------

    return {
        "status": status,
        "quality_score": quality_score,
        "summary": _clean_string(
            result.get(
                "summary"
            )
        ),
        "checks": validated_checks,
        "findings": validated_findings,
        "missing_acceptance_criteria":
            _clean_string_list(
                result.get(
                    "missing_acceptance_criteria",
                    [],
                )
            ),
        "uncovered_acceptance_criteria":
            _clean_string_list(
                result.get(
                    "uncovered_acceptance_criteria",
                    [],
                )
            ),
        "recommendations":
            _clean_string_list(
                result.get(
                    "recommendations",
                    [],
                )
            ),
        "approved_for_final_output": approved,
    }


# ============================================================
# REVIEW STORY
# ============================================================

def review_story(
    requirement: str,
    story_output: dict,
    business_analyst_output: dict,
    technical_output: dict,
    qa_output: dict,
    risk_output: dict,
    story_point_output: dict,
) -> dict:

    if not isinstance(
        requirement,
        str,
    ):
        raise ValueError(
            "requirement must be a string."
        )

    if not isinstance(
        story_output,
        dict,
    ):
        raise ValueError(
            "story_output must be a dictionary."
        )

    if not isinstance(
        business_analyst_output,
        dict,
    ):
        raise ValueError(
            "business_analyst_output must be a dictionary."
        )

    if not isinstance(
        technical_output,
        dict,
    ):
        raise ValueError(
            "technical_output must be a dictionary."
        )

    if not isinstance(
        qa_output,
        dict,
    ):
        raise ValueError(
            "qa_output must be a dictionary."
        )

    if not isinstance(
        risk_output,
        dict,
    ):
        raise ValueError(
            "risk_output must be a dictionary."
        )

    if not isinstance(
        story_point_output,
        dict,
    ):
        raise ValueError(
            "story_point_output must be a dictionary."
        )

    prompt = _build_prompt(
        requirement=requirement,
        story_output=story_output,
        business_analyst_output=business_analyst_output,
        technical_output=technical_output,
        qa_output=qa_output,
        risk_output=risk_output,
        story_point_output=story_point_output,
    )

    try:

        completion = client.chat.completions.create(
            model=MODEL,
            temperature=0.1,
            response_format={
                "type": "json_object"
            },
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

    except Exception as exc:

        if is_rate_limit_error(exc):

            raise GroqRateLimitError(
                "Groq API rate limit exceeded. Please try again in a few minutes."
            ) from exc

        raise Exception(
            f"Review Agent failed: {exc}"
        ) from exc

    content = (
        completion
        .choices[0]
        .message
        .content
    )

    if not content:
        raise Exception(
            "Review Agent returned an empty response."
        )

    try:

        result = json.loads(
            content
        )

    except json.JSONDecodeError as exc:

        raise Exception(
            "Review Agent returned invalid JSON."
        ) from exc

    return _validate_result(
        result
    )
