import json

import httpx
from groq import Groq

from app.config import GROQ_API_KEY, GROQ_STORY_MODEL
from app.services.groq_service import (
    GroqRateLimitError,
    is_rate_limit_error,
)


# ============================================================
# GROQ CLIENT
# ============================================================
#
# The Groq SDK default read timeout is 60 seconds. The multi-agent
# pipeline performs several sequential LLM calls, and a single call
# can legitimately take longer than 60 seconds under load. Increase
# the timeout so the Risk Agent does not fail with "Request timed out"
# while Groq is still processing.
#
# ============================================================

client = Groq(
    api_key=GROQ_API_KEY,
    timeout=httpx.Timeout(
        connect=10.0,
        read=300.0,
        write=300.0,
        pool=300.0,
    ),
    max_retries=5,
)


# ============================================================
# MODEL
# ============================================================

MODEL = GROQ_STORY_MODEL


# ============================================================
# ALLOWED RISK LEVELS
# ============================================================

ALLOWED_RISK_LEVELS = [
    "Low",
    "Medium",
    "High",
    "Very High",
]


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are the Risk Analysis Agent of StoryPilot AI.

You are an expert:

- Senior Product Manager
- Business Analyst
- Security Analyst
- QA Engineer
- Agile Product Owner

Your responsibility is to analyze an Agile user story and
identify realistic implementation, product, security,
technical, QA, and operational risks.

You receive information generated by other StoryPilot AI
agents.

The input may contain:

- User story
- Business value
- Acceptance criteria
- Definition of Done
- Assumptions
- Dependencies
- QA test scenarios
- Technical information

Your job is to identify risks that are directly relevant
to the requirement.

Do NOT invent unrelated risks.

============================================================
RISK CATEGORIES
============================================================

Consider applicable risks from these categories:

1. Functional Risk
2. Technical Risk
3. Security Risk
4. Authorization Risk
5. Data Risk
6. Integration Risk
7. Validation Risk
8. UI/UX Risk
9. Performance Risk
10. Availability Risk
11. Business Rule Risk
12. QA/Test Coverage Risk
13. Dependency Risk
14. Operational Risk
15. Compliance Risk

Only include categories that are actually relevant.

============================================================
RISK LEVEL
============================================================

Every risk must have one of these levels:

Low
Medium
High
Very High

Use:

LOW

When the impact and likelihood are both limited.

MEDIUM

When the issue could affect functionality or users but
has a reasonable mitigation.

HIGH

When the issue could significantly affect security,
business functionality, data, users, or production behavior.

VERY HIGH

When the issue could cause major security, financial,
business, compliance, or system impact.

============================================================
RISK ANALYSIS
============================================================

For every identified risk provide:

- Risk ID
- Category
- Risk
- Impact
- Likelihood
- Risk Level
- Mitigation
- Related Acceptance Criteria

The risk must be specific to the story.

Avoid generic statements such as:

"System may have bugs."

Instead provide useful risks such as:

"Incorrect evaluation of overlapping MFA rules could cause
users to receive unexpected authentication challenges."

============================================================
LIKELIHOOD
============================================================

Use:

Low
Medium
High

============================================================
IMPACT
============================================================

Use:

Low
Medium
High
Critical

============================================================
SECURITY
============================================================

Pay special attention to:

- Authentication
- Authorization
- Privilege escalation
- Sensitive data exposure
- Incorrect access control
- Configuration errors
- Security-rule bypass
- Unauthorized modifications

If the story has no security relevance, do not invent
security risks.

============================================================
ACCEPTANCE CRITERIA TRACEABILITY
============================================================

Every relevant risk should reference the acceptance
criteria that it affects.

Example:

"related_acceptance_criteria": [
    "AC001",
    "AC003"
]

If the risk does not directly relate to a specific
acceptance criterion, use an empty list.

============================================================
MITIGATION
============================================================

Every significant risk must contain a practical mitigation.

The mitigation should be something a real development,
product, or QA team can act upon.

Examples:

- Add server-side authorization checks.
- Add duplicate-rule validation at database level.
- Add automated regression tests.
- Validate rule precedence before deployment.
- Add audit logging for administrative changes.

============================================================
OUTPUT
============================================================

Return ONLY valid JSON.

Use EXACTLY this structure:

{
    "overall_risk_level": "Medium",
    "risk_summary": "",
    "risks": [
        {
            "risk_id": "R001",
            "category": "Security",
            "risk": "",
            "impact": "High",
            "likelihood": "Medium",
            "risk_level": "High",
            "mitigation": "",
            "related_acceptance_criteria": [
                "AC001"
            ]
        }
    ],
    "assumptions": [
        ""
    ],
    "dependencies": [
        ""
    ]
}

============================================================
OVERALL RISK
============================================================

overall_risk_level must be one of:

Low
Medium
High
Very High

The overall risk must reflect the most important risks
and the combined complexity of the story.

Do not simply choose the highest individual risk.

============================================================
RISK SUMMARY
============================================================

Provide a concise summary of the most important risks.

============================================================
ASSUMPTIONS
============================================================

List reasonable assumptions required to assess the risks.

Examples:

- Administrator permissions are enforced server-side.
- MFA rule conditions use predefined supported values.
- Existing authentication infrastructure evaluates rules.

Do not invent unnecessary assumptions.

============================================================
DEPENDENCIES
============================================================

List relevant technical or business dependencies.

Examples:

- Authentication service
- User directory
- Database
- Existing authorization framework
- Rule evaluation engine

If no meaningful dependency exists, return an empty array.

============================================================
QUALITY REQUIREMENT
============================================================

The output must be useful to:

- Product Manager
- Product Owner
- Developer
- QA Engineer
- Security Engineer
- Scrum Master

The analysis must be specific, actionable, and traceable.

Return ONLY JSON.
"""


# ============================================================
# PROMPT BUILDER
# ============================================================

def _build_prompt(
    story_output: dict,
    business_analyst_output: dict,
    qa_output: dict,
) -> str:

    story_json = json.dumps(
        story_output,
        indent=2,
        ensure_ascii=False,
    )

    business_analyst_json = json.dumps(
        business_analyst_output,
        indent=2,
        ensure_ascii=False,
    )

    qa_json = json.dumps(
        qa_output,
        indent=2,
        ensure_ascii=False,
    )

    return f"""
Analyze the following Agile user story and identify
realistic implementation and product risks.

============================================================
USER STORY AGENT OUTPUT
============================================================

{story_json}

============================================================
BUSINESS ANALYST AGENT OUTPUT
============================================================

{business_analyst_json}

============================================================
QA AGENT OUTPUT
============================================================

{qa_json}

============================================================
RISK ANALYSIS TASK
============================================================

Analyze:

- Functional risks
- Technical risks
- Security risks
- Authorization risks
- Data risks
- Integration risks
- Validation risks
- UI/UX risks
- Performance risks
- Business-rule risks
- QA coverage risks
- Dependency risks
- Operational risks

Only include risks relevant to the requirement.

Every meaningful risk should map to its relevant
acceptance criteria.

Provide practical mitigation for every risk.

Return ONLY valid JSON.
"""


# ============================================================
# VALIDATION HELPERS
# ============================================================

def _clean_string(
    value,
    default="",
) -> str:

    if value is None:
        return default

    if not isinstance(
        value,
        str,
    ):
        value = str(value)

    return value.strip()


def _validate_risk(
    risk: dict,
    index: int,
) -> dict:

    if not isinstance(
        risk,
        dict,
    ):
        risk = {}

    # --------------------------------------------------------
    # RISK ID
    # --------------------------------------------------------

    risk_id = _clean_string(
        risk.get("risk_id")
    )

    if not risk_id:
        risk_id = f"R{index:03d}"

    risk["risk_id"] = risk_id

    # --------------------------------------------------------
    # CATEGORY
    # --------------------------------------------------------

    risk["category"] = _clean_string(
        risk.get("category"),
        "Functional",
    )

    # --------------------------------------------------------
    # RISK
    # --------------------------------------------------------

    risk["risk"] = _clean_string(
        risk.get("risk")
    )

    # --------------------------------------------------------
    # IMPACT
    # --------------------------------------------------------

    impact = _clean_string(
        risk.get("impact"),
        "Medium",
    )

    if impact not in [
        "Low",
        "Medium",
        "High",
        "Critical",
    ]:
        impact = "Medium"

    risk["impact"] = impact

    # --------------------------------------------------------
    # LIKELIHOOD
    # --------------------------------------------------------

    likelihood = _clean_string(
        risk.get("likelihood"),
        "Medium",
    )

    if likelihood not in [
        "Low",
        "Medium",
        "High",
    ]:
        likelihood = "Medium"

    risk["likelihood"] = likelihood

    # --------------------------------------------------------
    # RISK LEVEL
    # --------------------------------------------------------

    risk_level = _clean_string(
        risk.get("risk_level"),
        "Medium",
    )

    if risk_level not in ALLOWED_RISK_LEVELS:
        risk_level = "Medium"

    risk["risk_level"] = risk_level

    # --------------------------------------------------------
    # MITIGATION
    # --------------------------------------------------------

    risk["mitigation"] = _clean_string(
        risk.get("mitigation")
    )

    # --------------------------------------------------------
    # ACCEPTANCE CRITERIA TRACEABILITY
    # --------------------------------------------------------

    acceptance_criteria = risk.get(
        "related_acceptance_criteria",
        [],
    )

    if not isinstance(
        acceptance_criteria,
        list,
    ):
        acceptance_criteria = []

    cleaned_acceptance_criteria = []

    for criterion in acceptance_criteria:

        criterion_text = _clean_string(
            criterion
        )

        if criterion_text:
            cleaned_acceptance_criteria.append(
                criterion_text
            )

    risk[
        "related_acceptance_criteria"
    ] = cleaned_acceptance_criteria

    return risk


# ============================================================
# RESULT VALIDATION
# ============================================================

def _validate_result(
    result: dict,
) -> dict:

    if not isinstance(
        result,
        dict,
    ):
        raise ValueError(
            "Risk Agent returned an invalid object."
        )

    # --------------------------------------------------------
    # OVERALL RISK
    # --------------------------------------------------------

    overall_risk_level = _clean_string(
        result.get(
            "overall_risk_level"
        ),
        "Medium",
    )

    if overall_risk_level not in ALLOWED_RISK_LEVELS:
        overall_risk_level = "Medium"

    result[
        "overall_risk_level"
    ] = overall_risk_level

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    result[
        "risk_summary"
    ] = _clean_string(
        result.get(
            "risk_summary"
        )
    )

    # --------------------------------------------------------
    # RISKS
    # --------------------------------------------------------

    risks = result.get(
        "risks",
        [],
    )

    if not isinstance(
        risks,
        list,
    ):
        risks = []

    validated_risks = []

    for index, risk in enumerate(
        risks,
        start=1,
    ):

        validated_risks.append(
            _validate_risk(
                risk,
                index,
            )
        )

    result[
        "risks"
    ] = validated_risks

    # --------------------------------------------------------
    # ASSUMPTIONS
    # --------------------------------------------------------

    assumptions = result.get(
        "assumptions",
        [],
    )

    if not isinstance(
        assumptions,
        list,
    ):
        assumptions = []

    cleaned_assumptions = []

    for assumption in assumptions:

        assumption_text = _clean_string(
            assumption
        )

        if assumption_text:
            cleaned_assumptions.append(
                assumption_text
            )

    result[
        "assumptions"
    ] = cleaned_assumptions

    # --------------------------------------------------------
    # DEPENDENCIES
    # --------------------------------------------------------

    dependencies = result.get(
        "dependencies",
        [],
    )

    if not isinstance(
        dependencies,
        list,
    ):
        dependencies = []

    cleaned_dependencies = []

    for dependency in dependencies:

        dependency_text = _clean_string(
            dependency
        )

        if dependency_text:
            cleaned_dependencies.append(
                dependency_text
            )

    result[
        "dependencies"
    ] = cleaned_dependencies

    return result


# ============================================================
# GENERATE RISK ANALYSIS
# ============================================================

def analyze_risks(
    story_output: dict,
    business_analyst_output: dict,
    qa_output: dict,
) -> dict:

    if not isinstance(
        story_output,
        dict,
    ):
        raise ValueError(
            "story_output must be a dictionary."
        )

    if not isinstance(
        business_analyst_output,
        dict,
    ):
        raise ValueError(
            "business_analyst_output must be a dictionary."
        )

    if not isinstance(
        qa_output,
        dict,
    ):
        raise ValueError(
            "qa_output must be a dictionary."
        )

    prompt = _build_prompt(
        story_output=story_output,
        business_analyst_output=business_analyst_output,
        qa_output=qa_output,
    )

    try:

        completion = client.chat.completions.create(
            model=MODEL,
            temperature=0.1,
            response_format={
                "type": "json_object"
            },
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

    except Exception as exc:

        if is_rate_limit_error(exc):

            raise GroqRateLimitError(
                "Groq API rate limit exceeded. Please try again in a few minutes."
            ) from exc

        raise Exception(
            f"Risk Agent failed: {exc}"
        ) from exc

    content = (
        completion
        .choices[0]
        .message
        .content
    )

    if not content:
        raise Exception(
            "Risk Agent returned an empty response."
        )

    try:

        result = json.loads(
            content
        )

    except json.JSONDecodeError as exc:

        raise Exception(
            "Risk Agent returned invalid JSON."
        ) from exc

    return _validate_result(
        result
    )
