import json

import httpx
from groq import Groq

from app.config import GROQ_API_KEY, GROQ_STORY_MODEL
from app.services.groq_service import (
    GroqRateLimitError,
    is_rate_limit_error,
)


# ============================================================
# GROQ CLIENT
# ============================================================
#
# The Groq SDK default read timeout is 60 seconds. The multi-agent
# pipeline performs several sequential LLM calls, and a single call
# can legitimately take longer than 60 seconds under load. Increase
# the timeout so the Technical Agent does not fail with
# "Request timed out" while Groq is still processing.
#
# ============================================================

client = Groq(
    api_key=GROQ_API_KEY,
    timeout=httpx.Timeout(
        connect=10.0,
        read=300.0,
        write=300.0,
        pool=300.0,
    ),
    max_retries=5,
)


# ============================================================
# MODEL
# ============================================================

MODEL = GROQ_STORY_MODEL


# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are the Technical Analysis Agent of StoryPilot AI.

You are an expert:

- Senior Software Architect
- Backend Engineer
- Frontend Engineer
- API Engineer
- Database Engineer
- Security Engineer
- DevOps Engineer

Your responsibility is to analyze an Agile user story and
identify the technical implementation impact.

You receive output generated by other StoryPilot AI agents.

Your analysis must help:

- Product Managers
- Business Analysts
- Developers
- QA Engineers
- Architects
- DevOps Engineers

understand what is technically required to implement the story.

============================================================
IMPORTANT
============================================================

Do NOT write production code.

Do NOT invent an architecture that is unrelated to the
requirement.

Do NOT assume technologies unless they are explicitly provided
or a reasonable product-level assumption is required.

Keep the analysis directly connected to the requirement.

============================================================
TECHNICAL AREAS
============================================================

Analyze applicable areas:

1. Frontend Changes
2. Backend Changes
3. API Changes
4. Database Changes
5. Authentication
6. Authorization
7. Security
8. External Integrations
9. Internal Service Dependencies
10. Data Validation
11. Business Logic
12. Error Handling
13. Performance
14. Logging and Monitoring
15. Configuration
16. Deployment
17. Testing
18. Migration

Only include areas that are relevant.

============================================================
FRONTEND ANALYSIS
============================================================

Identify applicable:

- New pages
- Existing page modifications
- Forms
- UI components
- Validation
- Loading states
- Error states
- Confirmation dialogs
- Permission-based UI
- Accessibility considerations

Do not invent UI functionality that the requirement does not
support.

============================================================
BACKEND ANALYSIS
============================================================

Identify applicable:

- New endpoints
- Existing endpoint modifications
- Request validation
- Response structure
- Business logic
- Service-layer changes
- Error handling
- Authorization
- Audit requirements

============================================================
DATABASE ANALYSIS
============================================================

Identify whether the story requires:

- New tables
- New columns
- Modified columns
- Relationships
- Constraints
- Indexes
- Unique constraints
- Data migration

If no database change is required, explicitly state that.

============================================================
API ANALYSIS
============================================================

For every relevant API provide:

- HTTP method
- Endpoint purpose
- Authentication requirement
- Authorization requirement
- Request information
- Response information

Do not invent exact endpoint names unless the requirement
provides enough information.

If the endpoint cannot be determined, describe the API
requirement without inventing a URL.

============================================================
SECURITY
============================================================

Pay special attention to:

- Authentication
- Authorization
- Privilege escalation
- Input validation
- Sensitive data
- Administrative operations
- Access control
- Audit logging
- Security configuration

For security-sensitive stories, server-side authorization
must be considered.

============================================================
DEPENDENCIES
============================================================

Identify dependencies such as:

- Existing services
- Authentication systems
- User directory
- Database
- External APIs
- Message queues
- Configuration
- Infrastructure

Only include meaningful dependencies.

============================================================
TECHNICAL ASSUMPTIONS
============================================================

List assumptions required to make the technical analysis.

Example:

"Existing authorization middleware is available for
administrator permission checks."

Do not create unnecessary assumptions.

============================================================
TRACEABILITY
============================================================

Where applicable, connect technical work to acceptance criteria.

Example:

{
    "area": "Backend",
    "requirement": "Validate duplicate MFA rules",
    "acceptance_criteria_ids": [
        "AC003"
    ]
}

This allows StoryPilot AI to maintain:

Requirement
→ User Story
→ Acceptance Criteria
→ Technical Implementation
→ QA Test Cases

============================================================
OUTPUT
============================================================

Return ONLY valid JSON.

Use EXACTLY this structure:

{
    "technical_summary": "",
    "frontend": {
        "required": true,
        "changes": [
            ""
        ]
    },
    "backend": {
        "required": true,
        "changes": [
            ""
        ]
    },
    "api": {
        "required": true,
        "changes": [
            {
                "method": "",
                "purpose": "",
                "authentication": "",
                "authorization": "",
                "acceptance_criteria_ids": []
            }
        ]
    },
    "database": {
        "required": false,
        "changes": [
            ""
        ]
    },
    "security": [
        {
            "requirement": "",
            "acceptance_criteria_ids": []
        }
    ],
    "integrations": [
        ""
    ],
    "dependencies": [
        ""
    ],
    "assumptions": [
        ""
    ],
    "error_handling": [
        ""
    ],
    "logging_and_monitoring": [
        ""
    ],
    "performance_considerations": [
        ""
    ],
    "testing_considerations": [
        ""
    ]
}

============================================================
QUALITY REQUIREMENTS
============================================================

The technical analysis must be:

- Specific
- Actionable
- Requirement-driven
- Traceable
- Realistic
- Consistent
- Suitable for development planning

Do not provide generic technical statements.

Return ONLY JSON.
"""


# ============================================================
# PROMPT BUILDER
# ============================================================

def _build_prompt(
    story_output: dict,
    business_analyst_output: dict,
) -> str:

    story_json = json.dumps(
        story_output,
        indent=2,
        ensure_ascii=False,
    )

    business_analyst_json = json.dumps(
        business_analyst_output,
        indent=2,
        ensure_ascii=False,
    )

    return f"""
Analyze the following user story from a technical
implementation perspective.

============================================================
STORY AGENT OUTPUT
============================================================

{story_json}

============================================================
BUSINESS ANALYST AGENT OUTPUT
============================================================

{business_analyst_json}

============================================================
TASK
============================================================

Identify the technical implementation impact.

Analyze:

- Frontend
- Backend
- APIs
- Database
- Security
- Integrations
- Dependencies
- Error handling
- Logging and monitoring
- Performance
- Testing

Connect technical changes to the acceptance criteria wherever
possible.

Do not invent unrelated architecture.

Return ONLY valid JSON.
"""


# ============================================================
# STRING HELPER
# ============================================================

def _clean_string(
    value,
    default="",
) -> str:

    if value is None:
        return default

    if not isinstance(
        value,
        str,
    ):
        value = str(value)

    return value.strip()


# ============================================================
# LIST HELPER
# ============================================================

def _clean_string_list(
    value,
) -> list[str]:

    if not isinstance(
        value,
        list,
    ):
        return []

    result = []

    for item in value:

        cleaned = _clean_string(
            item
        )

        if cleaned:
            result.append(
                cleaned
            )

    return result


# ============================================================
# FRONTEND VALIDATION
# ============================================================

def _validate_frontend(
    value,
) -> dict:

    if not isinstance(
        value,
        dict,
    ):
        value = {}

    required = value.get(
        "required",
        False,
    )

    if not isinstance(
        required,
        bool,
    ):
        required = False

    return {
        "required": required,
        "changes": _clean_string_list(
            value.get(
                "changes",
                [],
            )
        ),
    }


# ============================================================
# BACKEND VALIDATION
# ============================================================

def _validate_backend(
    value,
) -> dict:

    if not isinstance(
        value,
        dict,
    ):
        value = {}

    required = value.get(
        "required",
        False,
    )

    if not isinstance(
        required,
        bool,
    ):
        required = False

    return {
        "required": required,
        "changes": _clean_string_list(
            value.get(
                "changes",
                [],
            )
        ),
    }


# ============================================================
# API VALIDATION
# ============================================================

def _validate_api(
    value,
) -> dict:

    if not isinstance(
        value,
        dict,
    ):
        value = {}

    required = value.get(
        "required",
        False,
    )

    if not isinstance(
        required,
        bool,
    ):
        required = False

    changes = value.get(
        "changes",
        [],
    )

    if not isinstance(
        changes,
        list,
    ):
        changes = []

    validated_changes = []

    for change in changes:

        if not isinstance(
            change,
            dict,
        ):
            continue

        acceptance_criteria_ids = (
            change.get(
                "acceptance_criteria_ids",
                [],
            )
        )

        if not isinstance(
            acceptance_criteria_ids,
            list,
        ):
            acceptance_criteria_ids = []

        acceptance_criteria_ids = [
            _clean_string(item)
            for item in acceptance_criteria_ids
            if _clean_string(item)
        ]

        validated_changes.append(
            {
                "method": _clean_string(
                    change.get(
                        "method"
                    )
                ),
                "purpose": _clean_string(
                    change.get(
                        "purpose"
                    )
                ),
                "authentication": _clean_string(
                    change.get(
                        "authentication"
                    )
                ),
                "authorization": _clean_string(
                    change.get(
                        "authorization"
                    )
                ),
                "acceptance_criteria_ids":
                    acceptance_criteria_ids,
            }
        )

    return {
        "required": required,
        "changes": validated_changes,
    }


# ============================================================
# DATABASE VALIDATION
# ============================================================

def _validate_database(
    value,
) -> dict:

    if not isinstance(
        value,
        dict,
    ):
        value = {}

    required = value.get(
        "required",
        False,
    )

    if not isinstance(
        required,
        bool,
    ):
        required = False

    return {
        "required": required,
        "changes": _clean_string_list(
            value.get(
                "changes",
                [],
            )
        ),
    }


# ============================================================
# SECURITY VALIDATION
# ============================================================

def _validate_security(
    value,
) -> list[dict]:

    if not isinstance(
        value,
        list,
    ):
        return []

    result = []

    for item in value:

        if not isinstance(
            item,
            dict,
        ):
            continue

        acceptance_criteria_ids = (
            item.get(
                "acceptance_criteria_ids",
                [],
            )
        )

        if not isinstance(
            acceptance_criteria_ids,
            list,
        ):
            acceptance_criteria_ids = []

        acceptance_criteria_ids = [
            _clean_string(item_id)
            for item_id in acceptance_criteria_ids
            if _clean_string(item_id)
        ]

        result.append(
            {
                "requirement": _clean_string(
                    item.get(
                        "requirement"
                    )
                ),
                "acceptance_criteria_ids":
                    acceptance_criteria_ids,
            }
        )

    return result


# ============================================================
# COMPLETE RESULT VALIDATION
# ============================================================

def _validate_result(
    result: dict,
) -> dict:

    if not isinstance(
        result,
        dict,
    ):
        raise ValueError(
            "Technical Agent returned an invalid object."
        )

    return {
        "technical_summary": _clean_string(
            result.get(
                "technical_summary"
            )
        ),

        "frontend": _validate_frontend(
            result.get(
                "frontend"
            )
        ),

        "backend": _validate_backend(
            result.get(
                "backend"
            )
        ),

        "api": _validate_api(
            result.get(
                "api"
            )
        ),

        "database": _validate_database(
            result.get(
                "database"
            )
        ),

        "security": _validate_security(
            result.get(
                "security",
                [],
            )
        ),

        "integrations": _clean_string_list(
            result.get(
                "integrations",
                [],
            )
        ),

        "dependencies": _clean_string_list(
            result.get(
                "dependencies",
                [],
            )
        ),

        "assumptions": _clean_string_list(
            result.get(
                "assumptions",
                [],
            )
        ),

        "error_handling": _clean_string_list(
            result.get(
                "error_handling",
                [],
            )
        ),

        "logging_and_monitoring":
            _clean_string_list(
                result.get(
                    "logging_and_monitoring",
                    [],
                )
            ),

        "performance_considerations":
            _clean_string_list(
                result.get(
                    "performance_considerations",
                    [],
                )
            ),

        "testing_considerations":
            _clean_string_list(
                result.get(
                    "testing_considerations",
                    [],
                )
            ),
    }


# ============================================================
# GENERATE TECHNICAL ANALYSIS
# ============================================================

def analyze_technical(
    story_output: dict,
    business_analyst_output: dict,
) -> dict:

    if not isinstance(
        story_output,
        dict,
    ):
        raise ValueError(
            "story_output must be a dictionary."
        )

    if not isinstance(
        business_analyst_output,
        dict,
    ):
        raise ValueError(
            "business_analyst_output must be a dictionary."
        )

    prompt = _build_prompt(
        story_output=story_output,
        business_analyst_output=business_analyst_output,
    )

    try:

        completion = client.chat.completions.create(
            model=MODEL,
            temperature=0.1,
            response_format={
                "type": "json_object"
            },
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )

    except Exception as exc:

        if is_rate_limit_error(exc):

            raise GroqRateLimitError(
                "Groq API rate limit exceeded. Please try again in a few minutes."
            ) from exc

        raise Exception(
            f"Technical Agent failed: {exc}"
        ) from exc

    content = (
        completion
        .choices[0]
        .message
        .content
    )

    if not content:
        raise Exception(
            "Technical Agent returned an empty response."
        )

    try:

        result = json.loads(
            content
        )

    except json.JSONDecodeError as exc:

        raise Exception(
            "Technical Agent returned invalid JSON."
        ) from exc

    return _validate_result(
        result
    )
